#!/bin/bash
echo START!
for s in 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20
do
	python halo_weighing_mInside_new.py 0.59 $s
	python cumdist_mass_sigma_new.py mcrit200 halo_weighing_mInside.npy $s >> script_sigma_m80_mcrit200_deason.txt
done
